### ISSUE TITLE
Chart update wrong column names

### ISSUE THREAD

**Issue by kai2468** [highcharts/highcharts#12117]
#### Expected behaviour
Display the right column names when changing through chart.update with the data module

#### Actual behaviour
Column uses a previously defined column name instead

#### Live demo with steps to reproduce
https://jsfiddle.net/x89eq3hv/

Column names displayed as "Test1" and "Test"
Click update button
Column names now displayed as "Test" and "2" when it should be "1" and "2"

#### Product version
Latest

**Comment by sebastianbochan** [comment]
Hi @kai2468,
Thank you for contacting us. The reason of it is declaration of index in your second CSV. You refer to 1 and 2 categories. (1 means index 1 - Test not Test1). Categories are array indexed from 0.

Fixed demo:
- https://jsfiddle.net/BlackLabel/4uL67wv0/

For the further [support](http://www.highcharts.com/support) questions please use forum / stackoverflow or email.

**Comment by kai2468** [comment]
Think theres been a misunderstanding here, my original csv data has the columns set to "test1" and "test". My new data that I am passing into the csv property has the column names 1 and 2. I would expect these to overwrite the previous names, not reference them when updating the chart. The fix you proposed doesnt really fix anything here Im afraid

**Comment by pawelfus** [comment]
The problem here are names: "1" and "2". It seems that we treat those as numbers (well, that's correct) according to series mappings:
```js
    "seriesMapping": [{
      "x": 0,
      "y": 1
    }]
```

If we had information that "1" and "2" are actually names, not just numbers, then it works fine, demo: https://jsfiddle.net/kx2nr140/1/

```js
    "seriesMapping": [{
      "x": 0,
      "name": 0,
      "y": 1
    }]
```

I'm not sure if we should change this, let's compare with this example: https://jsfiddle.net/kx2nr140/2/ - what we have here is a completely different dataset, with numbers as x's that are translated to dates.

**Comment by kai2468** [comment]
Hmm ok makes sense. Thanks for that, with your explanation, I guess its not a bug then :)

**Comment by pawelfus** [comment]
Leaving the decision to @TorsteinHonsi :)
