### ISSUE TITLE
The stackLabels are misplaced when rotation is set.

### ISSUE THREAD

**Issue by raf18seb** [highcharts/highcharts#15129]
#### Actual behaviour
The longer text, the bigger is misplace of stackLabels.

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/tnv25pzq/

#### Product version
Highcharts 9.0.0

**Comment by PaulDalek** [comment]
It is a regression. The latest working version is `7.1.2`.

**Demo**
https://jsfiddle.net/BlackLabel/mg3u54dv/

Bisected to commit https://github.com/highcharts/highcharts/commit/ed7ea403acc4299600cf8dc5a7d98d53b9ce78b6.

**Comment by gustavoittner** [comment]
Meanwhile there is a workaround to this issue?

**Comment by PaulDalek** [comment]
Hi @gustavoittner 

You could try to make stack labels as HTML elements and rotate them through inline CSS with `transform: rotate`.

**Demo**
https://jsfiddle.net/BlackLabel/ym9gLr2z/

**Comment by gustavoittner** [comment]
Even in the HighCharts version 7.1.2, the stackLabels that are too large to fit the chart are not adjusted to fit. Another issue is that the stackLabels can overlap the series dataLabels. Is there any way that I could handle the collision between the stackLabels and the dataLabels giving stackLabels priority over dataLabels?

Current:
![current](https://user-images.githubusercontent.com/47633508/108098155-cc7fd380-7061-11eb-9bf4-107ba57adef8.png)

Expected (collision and fit handled):
![expected](https://user-images.githubusercontent.com/47633508/108098180-d43f7800-7061-11eb-9186-a3e11825a7ab.png)

Is there any way that I can achieve this behavior?

**Comment by KacperMadej** [comment]
@gustavoittner 
This looks like a different problem and should be reported in a different issue - this one is about the misplaced position after rotation. It looks like the priority is already in favor of stackLabels - maybe you could add a live demo?

**Comment by gustavoittner** [comment]
@KacperMadej 

In the fiddle I'm using version 7.1.2 which is supposed to have the expected behavior, but it still has some problems.

https://jsfiddle.net/3r8bp9dq/

But even in version 7.1.2 the result is not like image bellow:
![image](https://user-images.githubusercontent.com/47633508/108239257-75910180-7128-11eb-8d8f-925c200e5620.png)

**Different from the fiddle, in the image above:**
1. The stackLabels are not over the column stacks, only when they are adjusted to fit into the chart
2. When stackLabels are adjusted to fit into the chart, the possible collisions with series.dataLabels are resolved, giving priority to the stackLabel over the conflicted dataLabel

In the fiddle, for some reason, the second column stack has lost the dataLabel, even thought there is no collision happening. I don't know if it's gonna happen in current Highcharts version after the regression:
![image](https://user-images.githubusercontent.com/47633508/108240154-534bb380-7129-11eb-9bb6-6a782072e67d.png)

**Comment by KacperMadej** [comment]
It's (hopefully) not going to happen because you have pointed this out, so thank you.
Demo of the second problem (wrong overlap detection): https://jsfiddle.net/BlackLabel/9nkbr7sf/

**Comment by isiemers** [comment]
The original issue (stack labels with set rotation being horizontally offset, proportionally to the length of the label) is still present in  version 10.3.2

**Comment by pawellysy** [comment]
Thanks for your input @isiemers! We are in process of refactoring this module. Any updates will be posted in the thread, or linked PR's.
