### ISSUE TITLE
Annotation with measure type "x" does not work as expected

### ISSUE THREAD

**Issue by felipejacobsexternal** [highcharts/highcharts#15508]
Hi there!
When I'll try to implement the annotation measure tools I'd realize that when I don't want to use the range selector config, the measure tool for "x" doesn't show the labels at all:
![image](https://user-images.githubusercontent.com/62137150/114742570-2ba15200-9d4c-11eb-955b-b5b6c4c69ff7.png)

But if I put the rangeSelector enabled the behavior works as expected
![image](https://user-images.githubusercontent.com/62137150/114743393-f0ebe980-9d4c-11eb-85a2-e7b20fdfaf59.png)

#### Live demo with steps to reproduce
https://jsfiddle.net/fpmu4n2o/83/

#### Affected browser(s)
Google Chrome

am I not implementing it correctly?
Thanks in advance and good works anyway!

**Comment by pawelfus** [comment]
There is an option, for example:
```js
    navigation: {
      bindings: {
        measureX: {
          annotationsOptions: {
            typeOptions: {
              label: {
                verticalAlign: 'bottom'
              }
            }
          }
        }
      }
    }
```
`annotationsOptions` are the same as specific annotation type for example: https://api.highcharts.com/highstock/annotations.measure

Using the config above (forcing `verticalAlign`) should resolve the issue: https://jsfiddle.net/BlackLabel/hey6qb1c/

It's a bug in docs, that `verticalAlign` (and many other options) are missing. More available options are listed here: https://api.highcharts.com/highstock/annotations.labelOptions

**Comment by felipejacobsexternal** [comment]
> There is an option, for example:
> 
> ```js
>     navigation: {
>       bindings: {
>         measureX: {
>           annotationsOptions: {
>             typeOptions: {
>               label: {
>                 verticalAlign: 'bottom'
>               }
>             }
>           }
>         }
>       }
>     }
> ```
> 
> `annotationsOptions` are the same as specific annotation type for example: https://api.highcharts.com/highstock/annotations.measure
> 
> Using the config above (forcing `verticalAlign`) should resolve the issue: https://jsfiddle.net/BlackLabel/hey6qb1c/
> 
> It's a bug in docs, that `verticalAlign` (and many other options) are missing. More available options are listed here: https://api.highcharts.com/highstock/annotations.labelOptions

Thanks so much, @pawelfus, but, I don't understand why if I set "rangeSelector.enabled" to false the label disappears.

**Comment by pawelfus** [comment]
> Thanks so much, @pawelfus, but, I don't understand why if I set "rangeSelector.enabled" to false the label disappears.

That is of course a bug, we will fix it :) Sorry for not making this clear! Added correct label to the issue

**Comment by felipejacobsexternal** [comment]
Hi there! Sorry for insist :)
I have tried the solution but it still producing a weird result:

**The scenario:**

> We want to append a horizontal measuring for chart data without using the default range selector.

**The expected result:**
> When a horizontal measure is appended we expect to see the label with the result for this measuring. We don't care if we are using the default range selector or not.

**What we get:**
> We can append the measure tool for both Axis and vertical axis with the expected label with the data, but when we append the horizontal measure tool we don't get the label with the information data.

**The evidence:**
[https://jsfiddle.net/2g19uo6p/](https://jsfiddle.net/2g19uo6p/)

We try to set the configuration to force the position as you recommended:
```
navigation: {
      bindings: {
        measureX: {
          annotationsOptions: {
            typeOptions: {
              label: {
                verticalAlign: 'bottom'
              }
            }
          }
        }
      }
    }
```
But it still not working for us.

Thanks in advance!
Regards!
