### ISSUE TITLE
Highcharts file service returning invalid content-encoding value when downloading zip content

### ISSUE THREAD

**Issue by ryanrath** [highcharts/highcharts#16926]
#### Expected behaviour
When issuing the following command `curl -fLSs --compressed https://code.highcharts.com/zips/Highcharts-4.2.5.zip` the response `content-encoding` header should contain a valid value ( https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Encoding ). 

#### Actual behaviour
The response header `content-encoding` actually contains `UTF-8`, curl ( version 7.57.0+) will not download the requested zip file and generates the following error message: `curl: (61) Unrecognized content encoding type. libcurl understands deflate, gzip, br content encodings.` 

#### Product version
Highcharts 4.2.5, but I have a feeling that this is a service / server level problem and not necessarily a product version problem.

#### Affected browser(s)
N/A

**Comment by ryanrath** [comment]
I wasn't sure where to report this so if there's someplace else that is better suited for a problem of this nature just let me know. Thanks!

**Comment by ryanrath** [comment]
For what it's worth, the versions that have this problem are: 3.0.4 -> 3.0.9 and 4.0.0 -> 4.2.5

**Comment by KacperMadej** [comment]
Hi @ryanrath ,

Thank you for reporting the problem. I will pass it to our website developers.

Could you check if this wasn't a one-time event? Is the problem still happening?
Is this happening for you for more up-to-date code versions?

A bonus, optional, and not related to resolving the problem question: Could you let us know more about your use case? This issue is based on a rather uncommon usage.

**Comment by ryanrath** [comment]
Hi @KacperMadej , 

I just double checked and the problem is still occurring when attempting to curl download the zip versions of Highcharts v3.0.4 -> v3.0.9 and then v4.0.0 -> v4.2.5. 

Sure, so our project is written in PHP and we utilize Composer to handle our dependency management. Under the hood Composer ( and PHP ) utilizes curl to retrieve files. This problem didn't present itself till now due to our standard build OS being fairly old ( Centos7 ) and thus having an older version of PHP / curl that merrily ignored the fact that it was receiving an invalid content-encoding header. Now that we're updating our build OS to something more recent the version of PHP & curl is more up to date and started refusing to download the version of Highcharts we have pinned. As a stop gap I've updated to using v4.2.7, which works after a few minor tweaks to our testing code. I've also added a task to our roadmap to update to the latest version of Highcharts. 

If there's any other information or testing you need just let me know.

Thanks!

**Comment by KacperMadej** [comment]
@ryanrath 
All this should be fixed now. Please give it a try and if you could confirm that everything is working fine we could close the issue.

**Comment by ryanrath** [comment]
@KacperMadej 

So I just re-tested and am getting the following error message when testing: ```curl: (22) The requested URL returned error: 403`.  I tried changing up the method of downloading the zip files in my test script and all of them return a 403 Forbidden for all highcharts versions: 
- `curl -fLSs --compressed https://code.highcharts.com/zips/Highcharts-4.2.7.zip > Highcharts-4.2.7.zip`
- `curl -fLSs https://code.highcharts.com/zips/Highcharts-4.2.7.zip > Highcharts-4.2.7.zip`
- `wget https://code.highcharts.com/zips/Highcharts-4.2.7.zip`

Maybe the fix was to disable these urls? If so could you provide the correct url to download these files? 

Thanks!

**Comment by ryanrath** [comment]
@KacperMadej 
Just tested a bit more and it looks like, for versions 2.3.2 and 4.2.7 the following url works: `http://code.highcharts.com/zips/Highcharts-4.2.7.zip`. Not sure why it's only those two versions but *shrug* thought you should know. 

Thanks!

**Comment by KacperMadej** [comment]
This is probably due to caching. The server has no enforcement for HTTPS over HTTP and it was recently (this morning) maintained with an error fixing update.

**Comment by ryanrath** [comment]
@KacperMadej 

Sounds good, testing again this morning it looks like v4.2.2 -> v9.3.1 are working now. I'm still getting a 403 for v4.2.0 and older but I'm guessing that it's probably just down to caching as you said. I can test a little bit later to see if the rest of the versions are available but it does seem like this is all set now. 

Thanks!
