### ISSUE TITLE
HighStock:2.1.7 x axis label offset is wrongly calculated. All the label is displayed below the chart

### ISSUE THREAD

**Issue by dreamershl** [highcharts/highcharts#4488]
I encounter a very strange error after upgrading to the 2.1.7 from 2.1.5. The following is what I figure out. I believe the check on 0 should be done before cache the label box offset. 
![image](https://cloud.githubusercontent.com/assets/1271739/9350539/528d9524-4684-11e5-91dd-7ced12ad8cef.png)
- After click the year 5 button, my app changes the data and "redraw()" the chart.
  The first label is "2010". Because it is out of the range, it causes the following 0 box created and cached

![image](https://cloud.githubusercontent.com/assets/1271739/9350637/05b526a8-4685-11e5-89ff-42a6df7558cf.png)

![image](https://cloud.githubusercontent.com/assets/1271739/9350570/9a565db4-4684-11e5-957a-82fb7fac035e.png)
- Then all other years label just uses the cached BBox value, which all are 0. 

Then all the chart x axis label is wrongly positioned in the chart. 

Why does the first "2010" tick trigger the whole calculation process? I believe it is because of the following range check. Its left position is -27.247037374658156 which is less than the left bound. 

![image](https://cloud.githubusercontent.com/assets/1271739/9350734/cda6b8b6-4685-11e5-90d6-a1c7f698e23e.png)

**Comment by pawelfus** [comment]
Could you setup jsFiddle demo with that issue?

**Comment by dreamershl** [comment]
Will try to do it. Thx

**Comment by dreamershl** [comment]
can't recreate this issue in the jsFiddle. But after I add the empty check before cache, the issue is fixed. Logically it is also not so right. The cache is for all same length of number string. But the first record is invisible, doesn't mean the second one is invisible too.

And my current chart period switching is also too complex. Need time to reflect all the process. Thanks.

**Comment by pawelfus** [comment]
Without live demo it would be hard to pinpoint the issue and provide the best fix. Just note, that labels are at first place rendered then, later, placed at correct places. 

And I think, that period switching should affect the chart the same way as using static data - so I would try to use that static data. 

Also, please try out 2.1.8 version, where bug-or-two with caching is fixed.

**Comment by dreamershl** [comment]
Thanks for the suggestion. I have migrated to the latest version, 2.1.8. my app still encounter same issue. I believe my current complex period switch may play a part. So I will try to reflect my current process first. Temporarily, I stop the cache when the box is empty for the number string first. Thanks again.

**Comment by pawelfus** [comment]
Any updates on it? Shall I close this ticket?

**Comment by pawelfus** [comment]
Closing due to inactivity.
