### ISSUE TITLE
Boost module has many limitation that makes it unusable 

### ISSUE THREAD

**Issue by onemenny** [highcharts/highcharts#5223]
I'm having several difficulties with the boost module known limitations that I tried to address in other threads before and are still not resolved. 
1. [Area lines are not drawn](https://github.com/highcharts/highcharts/issues/5136): while the assumption that area line is useless for more than X datapoint is logically correct, the boost module is still better performing whit less data points than X. specifically if you have 50 series with 500 points each the tooltip performance (also initial rendering and destroy) are _much_ better with canvas than SVG.  So I do not think that drawing area without the line should be "automatically" handled according to the threshold. 
2. Point markers are not drawn on line-type series: my arguments for area chart stands here as well. More ever, if you want to emphasizes where there are missing datapoints than markers are your best option. Consider having a series that on the first third is dense, on the second third has no data points, and on the third third is dense again - only marker can give the user to detect it at first glance. Moreever if you want to emphesize specific series (<500 points) with marker against large series (>5000 points) you cannot do it with the boost module. 
3. Zones and negativeColor don't work: again, this is very frustrating since zones makes things mush easier when you want to color segments of a series but you cannot do it with the boost module. Which leads you adding additional series just for that - not elegant 
4. Columns are always one pixel wide: my previous arguments stand here as well - you can have a column series with line series and you don't want the column to look awkward with 1 pixel limitation 

Other open source implementations do not have such limitations on their canvas view. If Highcharts users wants a performance boost that IMHO that user is willing to throw away animations, maybe sharpness, but not basic chart functionality. Ever since the boost module came to live (and I know I was one of the triggers) I find it hard to relay on. I expect the above limitation to be user options and not constraints.  

Please advice. 

Resources: 
[Lagging tooltip perforamnce](http://jsfiddle.net/onemenny/s2172kon/1/): 50 series, 500 datapoints each, no canvase
[Great tooltip performance](http://jsfiddle.net/onemenny/s2172kon/2/): 50 series, 500 datapoints each, with canvase

Other threads: 
https://github.com/highcharts/highcharts/issues/4948
https://github.com/highcharts/highcharts/issues/5136

**Comment by TorsteinHonsi** [comment]
Thanks for your input!

There are no technical limitations on the canvas technology or the Boost module itself regarding these issues, it is just that the Boost module is still a work in progress, and competing against other parts of Highcharts for priority. While I do agree with you on the points above, we have to consider where to invest our time compared to for example the feature requests listed at http://highcharts.uservoice.com.

The current implementation of the Boost module is focused on getting the best performance for hundreds of thousands of data points in a small number of series, so we didn't really focus on what happens with scarce data. But as always, if our users want us to focus on that, we will.

As for the practical implementation, I think your number 1, 2 and 4 should be feasible without too much work, except we need to do some reorganizing because we currently have only one stroke and one fill for each series. Your number 3, zones, would require a bit more work, but of course everything is doable.

**Comment by onemenny** [comment]
I cannot compete with the user voice, as long as the boost module is a "module" and not an integral part of the core. basically what you are telling me is that Highcharts performance is limited and not a high priority, since the boost module is only partially implemented and is good if you only have 1 series. I cannot disagree more. Is this your final state? Is there any other resolution?

**Comment by TorsteinHonsi** [comment]
> basically what you are telling me is that Highcharts performance is limited and not a high priority

That's not at all what I'm telling you! I'm saying we are working on this together with other parts of the library, but of course we have many things fighting for priority. 

> Is this your final state? 

Of course not! As you see I labeled this issue an enhancement. We will continue development on the Boost module. It doesn't mean we are able to throw all other development work over board and spend time on this right now.

**Comment by onemenny** [comment]
OK, I'm not realy sure what to do here. Hope this will be resolved soon.

**Comment by onemenny** [comment]
@cvasseng are these issue resolved in 5.10 ?
When are you going to announce what changes where made, and what is the status of webGL?

**Comment by cvasseng** [comment]
The change log and an announcement on the current state of all things boost will come after easter (along with updated documentation and so on). 

We're currently testing the waters a bit with the changes introduced in 5.0.8. When it comes to the things you mention in you OP, point markers are now working, but the status of the other issues remain the same for now. That's not to say they won't get addressed.

As a summary, the main focus this round has been to optimize for charts with large numbers of series, as well as extending support to include things like treemap/heatmap/bubble series, and general performance optimizations.

**Comment by onemenny** [comment]
@cvasseng Thank you for you answer,
Point 1 & 4 are super crucial, the inability to draw area or column chart (normally) makes this module useless. I hope to see these feature in the near future as potential competitors have recently spawn in the market

**Comment by prasadmvd** [comment]
Hi, Please let me know
Above points are fixed or not? Especially Point No:3
Thank you

**Comment by pawelfus** [comment]
Hi @prasadmvd  - point no. 3 is not implemented, demo: http://jsfiddle.net/BlackLabel/9xnk0r81/ - at this moment only markers were added to the boost module.

**Comment by agardiol** [comment]
The point 3 (zones) works in latest version (March 25th, 2022) but not with className attribute in zones (only color attribute works). Will this be fixed ?
Best regards.

**Comment by pawellysy** [comment]
Hello @agardiol, could you share the demo, where the issue is reproduced? Thanks!

**Comment by agardiol** [comment]
Here is a test case: http://jsfiddle.net/agardiol/627Ljkox/51/
Just (un)comment `//boostThreshold: 1,` to see the difference.
className is not taken into account in boost mode, but the color attribute is used.

**Comment by aetasoul** [comment]
Hi,
the point 3 seems to work as pointed out by @agardiol 

In my series I have near 2k points, and it is very slow to load, with just 100 points it's super fast

**Comment by karolkolodziej** [comment]
@aetasoul have you tried his workaround? 
With that and boost enable do you still have trouble with performance?

**Comment by aetasoul** [comment]
> @aetasoul have you tried his workaround? With that and boost enable do you still have trouble with performance?

Hi @karolkolodziej 
Yes, I'll try to share an example

**Comment by Miteshdv** [comment]
When I used Bubble Chart with Boost mode , the Circles are Pixelated and also the Y axis become same. so we dont get correct bubble values

<img width="611" height="97" alt="Image" src="https://github.com/user-attachments/assets/e84932cb-47d4-4259-a368-4ff2636f7f97" />

**Comment by K009** [comment]
Thanks for your input, @Miteshdv. Let’s continue the discussion in the issue you opened: https://github.com/highcharts/highcharts/issues/23772.
