### ISSUE TITLE
Stacking in areaspline series with negative values

### ISSUE THREAD

**Issue by Izothep** [highcharts/highcharts#5671]
Refering to SO topic: http://stackoverflow.com/questions/39392424/highcharts-area-chart-stacking-with-series-containing-negative-and-positive

I think that right now stacked area series with negative points may not be drawn correctly.

Live example of issue:
https://jsfiddle.net/tjmpe6se/11/

I think it may be good idea to make a different algorithm for stacking area series with negative values. 

Possible related to #1910

**Comment by oysteinmoseng** [comment]
I agree, the behavior from Highcharts 2 seems logical for some use cases

**Comment by TorsteinHonsi** [comment]
It does for this case, but the problems arise when you have mixed positive and negative values in the same series. Then [the current model makes sense](https://jsfiddle.net/highcharts/tjmpe6se/13/). With columns it is different, we can stack each item as [either negative and positive](https://jsfiddle.net/highcharts/tjmpe6se/14/), and don't have to mind the interpolated areas.

To get the same effect in area charts, my advice is to use separate [stack](http://api.highcharts.com/highcharts/series%3Carea%3E.stack) options: https://jsfiddle.net/highcharts/tjmpe6se/15/.

**Comment by sebastianbochan** [comment]
Maybe we should consider to set a parameter which will define "stacking model" ?

**Comment by d6teo** [comment]
With area charts, the `stack` option is useful when we have series with either only positive or only negative values, [see chart2](https://jsfiddle.net/tjmpe6se/16). 
When a series contains both positive and negative values: 
- using the `stack` option results in correct display of individual series, but IMHO the stacking purpose is not achieved, because a series can get "overlapped" [see chart 3](https://jsfiddle.net/tjmpe6se/16). 
- not using the `stack` option results in aggregation of chart's series, which represents the correct overall result, but individual series display is not correct (thatis, we lose the curve of data in the series)
I agree with @sebastianbochan , i think the best choice is to have an option that will actually STACK series values on top(for positive values) or on bottom(for negative values) of the chart (the behavior that was present in Highcharts v2)

**Comment by TorsteinHonsi** [comment]
The logic difference between column stacking and area stacking is [handled here](https://github.com/highcharts/highcharts/blob/v4.2.6/js/parts/ColumnSeries.js#L56-L57), as a result of issue #1910.

Just to summarize, as a minimal pair, notice the difference:
* In a column stack, point values are placed in different stacks, one for positive and one for negative values: https://jsfiddle.net/highcharts/tjmpe6se/18/.
* In an area stack, all points (for a given category) are accumulated, so negatives are simply substracted from positives: https://jsfiddle.net/highcharts/tjmpe6se/19/.

Actually I'm not sure how an area chart with separate negative stacks would look. In contrast to the column chart, which only has to draw elements for the actual points, we have to draw the area itself for the area chart. With separate stacks, we would need two areas, one for the positive stack and one for the negative, and I don't know how we should handle the crossing over.

**Comment by TorsteinHonsi** [comment]
I was able to bring back the old Highcharts 2.x behaviour by overwriting a couple of prototype properties and setting `connectNulls` to true: http://jsfiddle.net/highcharts/0o61t9cr/2/.

However, at this point we can't make it an option because it still breaks with the same cases as #1910.

**Comment by simPod** [comment]
Do I understand this is very complicated issue that won't be solved in near future? Thanks!

**Comment by pawelfus** [comment]
Just to clarify: if we want to use separate stacks for negatives and positives, then we can use `stack` option to handle this, for example: http://jsfiddle.net/0o61t9cr/5/ - of course, this doesn't resolve issue with crossings..

**Comment by simPod** [comment]
@pawelfus I confirm it works. So far I haven't encountered a case where it wouldn't

**Comment by simPod** [comment]
@pawelfus tried your solition

But sometimes positive stacks start in negative y values http://jsfiddle.net/a4eyxxzm/

![image](https://user-images.githubusercontent.com/327717/32281496-44393968-bf1f-11e7-8b86-02731237ad44.png)

**Comment by pawelfus** [comment]
@simPod it should be `stack` not `stack_type`: http://jsfiddle.net/a4eyxxzm/1/

**Comment by simPod** [comment]
@pawelfus ah my bad. Thanks!

**Comment by ismusidhu** [comment]
I've done a [workaround](https://github.com/highcharts/highcharts/issues/8517#issuecomment-399516509) for stacked area chart. May want to check if it works for area spline also

**Comment by randalvance** [comment]
Any progress on this one? We also need this functionality in our stacked area chart. Thanks.

**Comment by pawelfus** [comment]
Hi @randalvance It's quite complicated solution and we haven't had the time to prioritize it.

**Comment by madepiet** [comment]
### Also related to this matter

#### Expected behaviour
A clearly defined / standardized way of displaying this kind of data in different series types -different algorithms for stacking area series with negative values. Negative and positive values should be stacked separately, as in the column series.
![area](https://user-images.githubusercontent.com/39968065/81921910-99447b80-95db-11ea-9585-c74fc69e6d1e.png)


#### Actual behaviour
In the stacked column, it works as expected, but in the stacked area a positive value looks good, but negative values take the threshold of the last point in the C (600) series and draw -800 from it: that's why it goes out -200, then A -200-200 = -400

Stacked column:
https://jsfiddle.net/BlackLabel/k4f832Lm/

Stacked area:
https://jsfiddle.net/BlackLabel/4r7moaw2/

**Comment by simPod** [comment]
.

**Comment by benelliott** [comment]
bump
