### ISSUE TITLE
linearGradient in plotBand that overlaps edge of chart

### ISSUE THREAD

**Issue by drmrbrewer** [highcharts/highcharts#6257]
#### Expected behaviour

Where a `plotBand` starts in the visible chart area, and extends over the right edge and off the visible chart area, I would expect any gradient effects applied to the whole `plotBand` to be respected, so that the `plotBand` is simply cut short at the edge of the chart.

#### Actual behaviour

The `plotBand` seems to be truncated at the chart edge, without any adjustment to the linearGradient inside, so that the linearGradient is no longer correct because it has been applied to the truncated width.

#### Live demo with steps to reproduce

http://jsfiddle.net/bfp4epum/2/

Both `plotBands` in the above share the same width and `linearGradient` color, but because the second one is truncated, the `linearGradient` has been applied to the truncated width, and the effect is not as expected.

I appreciate the reasons for this, and there is a complicated way that the user can split up the `plotBands` into parts and apply different `linearGradients` to the different parts (see e.g. [here](http://jsfiddle.net/sf29w043/)), but really I'd expect this to be handled automatically by highcharts... so you just set the position and width and color of the `plotBand`, and highcharts deals (in the best way it knows how) with a situation where the `plotBand` does not fit entirely within the visible chart area.  

#### Affected browser(s)

Any.

**Comment by pawelfus** [comment]
Hi @drmrbrewer 

Thanks for reporting. Actually it's a duplicate of #4849. At this moment, plotBands are shapes rendered within the plotting area, not extending under a clip path.

**Comment by drmrbrewer** [comment]
So @pawelfus is this something that is likely to be fixed (or rather improved) in the near future, or do I have to go through the pain of doing it "manually" by breaking into multiple parts based on a number of different scenarios relating to where the gradient parts fall relative to the chart edge?

**Comment by pawelfus** [comment]
The problem here is that Axis doesn't have a clip path, so extending plotBand causes wrong rendering, see: http://jsfiddle.net/bfp4epum/3/

We can create our own clip rect and apply to such plotBand, what do you think: http://jsfiddle.net/bfp4epum/4/ ? I think this is much better than manually finding correct gradient.

Note: solution is not as simple as the example above, because we need to consider also label placements, ordinal axis, axis breaks etc.

**Comment by drmrbrewer** [comment]
The second solution looks pretty neat to me.  Is this something that might be modified in the source, or would this be an adhoc solution for a particular use-case by way of overriding the core function like this?

**Comment by pawelfus** [comment]
Oh, it's not overriding any of the core functions, it extends core functions. It's a recommended way to create plugins for Highcharts ([details](http://www.highcharts.com/docs/extending-highcharts/extending-highcharts)). So it can be safely used with different versions, for example:

- 4.2.0: http://jsfiddle.net/bfp4epum/5/
- 4.2.7: http://jsfiddle.net/bfp4epum/6/
- 5.0.0: http://jsfiddle.net/bfp4epum/7/

For example you can create a file "highcharts-6257.js" with the plugin content (code: `(function (H) { ... })(Highcharts);`, then include this as any other Highcharts plugin in the HTML, just after `highcharts.js` file.

**Comment by drmrbrewer** [comment]
OK sorry that's what I meant really... is this sort of thing likely to be something that will be added into the source, so that no extension is required, or will it always require an extension as per your demos?

**Comment by pawelfus** [comment]
Of course, it should be fixed in the core, though I can not predict ETA for this issue.

**Comment by drmrbrewer** [comment]
OK, that's good.

BTW I tried out the behaviour of your solution with pan and zoom enabled:

http://jsfiddle.net/bfp4epum/8/

It seems that when you zoom in and pan left/right, the gradient in the first plotBand is still incorrectly rendered, i.e. based on the truncated width.

**Comment by TorsteinHonsi** [comment]
@pawelfus I think this approach should be pretty safe when it comes to ordinal axes, breaks and stuff. The axis.width should be the same regardless.

It probably also means we can remove the logic that makes the plot band stay within the extremes, so the added overhead with the clipping is probably compensated for. 

We need to check how polar axes are affected though, they can't have a rectangular clipping region, and if we let the plot band go outside the extremes, it may wrap around the origin of the axis.

**Comment by pawelfus** [comment]
Adding issue with labels: http://jsfiddle.net/bfp4epum/9/ (it also applies correction for the left side of the band).

**Comment by drmrbrewer** [comment]
This is like watching a magic show!

**Comment by drmrbrewer** [comment]
Is this likely to make it into a highcharts release anytime soon?  Thanks!

**Comment by pawelfus** [comment]
I will take a look

**Comment by KacperMadej** [comment]
@TorsteinHonsi: Opening since the fix is reverted. Commits order is looking suspicious or is it just me?

**Comment by TorsteinHonsi** [comment]
I had to revert the changes as they broke the test suite for oldIE.

**Comment by drmrbrewer** [comment]
@KacperMadej @TorsteinHonsi any chance of reviving this one?  Thanks :)

**Comment by drmrbrewer** [comment]
@KacperMadej @pawelfus @TorsteinHonsi would be great if this issue could be resolved finally!

BTW looks like the way in which svg paths are specified has changed a bit since v.5.0.7 (was a linear array, now an array of arrays)... the following is a slightly revised version of the last example from @pawelfus [here](https://github.com/highcharts/highcharts/issues/6257#issuecomment-273502674):

http://jsfiddle.net/dx5yt6g9/

**Comment by pawelfus** [comment]
Thanks for the updated workaround @drmrbrewer ! That's correct, we have changed how paths are defined.

Could you elaborate what do you mean by any number and position of plotBands? Thanks!

**Comment by drmrbrewer** [comment]
@pawelfus at the moment the jsfiddle example linked just above is hardcoded for the specific example of exactly two plotBands with the second one overlapping the boundary of the visible chart:

      originalPath[2][1] = originalPath[3][1] = fixedTo;
      originalPath[0][1] = originalPath[1][1] = fixedFrom;

But of course the in the general case there may be a different number of plotBands, and there may or may not be any overlap.  And some may have labels, while others do not.

**Comment by pawelfus** [comment]
Hm.. no, no. It's left and right boundary of the plotBand: `fixedTo` modifies the right edge, while `fixedFrom` modifies the left edge:

![Screen Shot 2020-07-06 at 16 49 46](https://user-images.githubusercontent.com/1453926/86606948-f1c74200-bfa8-11ea-99d8-937e0d72cbcd.png)

If you have any example where it fails (except 3D and polar - we are aware of this limitations) then let us know - the more information we have, the better solution we can implement. For now we don't have plans to implement this, so I can't provide you any ETA.

**Comment by drmrbrewer** [comment]
You're right of course... it does seem to be a general solution.  Here is an example with three plotbands:

http://jsfiddle.net/dx5yt6g9/

How easy is it to "have the best of both worlds", which is:

(a) to have the gradients rendered based on the *full* band width (like the example above)
(b) the labels place based on the *visible* band width (like what happens without the workaround: http://jsfiddle.net/qgwfkr84/)

On balance I think it is preferable to centre the labels within the visible part.  If that is not possible, at least they should be truncated within the visible part.

**Comment by pawelfus** [comment]
Just for future refence:
(b) - Today, (b) is much easier, sice we have proper alignment for these labels too, PoC: http://jsfiddle.net/BlackLabel/ab6ksrt1/

> On balance I think it is preferable to centre the labels within the visible part of the band.

Unless `labels.align` is set to 'left' or 'right'. You can test it in the above demo too, should work.

**Comment by KacperMadej** [comment]
~ _a further activity occurs_ ~
