### ISSUE TITLE
Line visible for line chart with navigator when no values

### ISSUE THREAD

**Issue by mynameiswhat1** [highcharts/highcharts#6645]
#### Expected behaviour
 Using Highstock, when in a line chart I use the navigator to select an area with a gap in the chart data, no line should be drawn in the chart, for that selected area.

#### Actual behaviour
Lines are being drawn for a area of the chart where there is no data, when only that area is selected using the navigator. 

#### Live demo with steps to reproduce

Run the following demo and, with the navigator, select to view only the area with the data gap

http://jsfiddle.net/r5saqed0/

as in the following image:

![Image of Issue](https://preview.ibb.co/nJGiWQ/lines.jpg)

Related with the folowing issue described in forum: https://forum.highcharts.com/post134399.html

#### Affected browser(s)
At least Chrome 58.0.3029.81 (64-bit)

**Comment by mynameiswhat1** [comment]
If dataGrouping.enabled is set to false, the problem does not occur. However, it occurs when it is enabled.

**Comment by mynameiswhat1** [comment]
Hello, 
Is there an estimate for when this issue will be solved?
Thank you.

**Comment by pawelfus** [comment]
*Internal note:*
Actually, it works exactly as `gapSize` is defined. In fact, we are zooming in this case between two points and [`gapSize`](http://api.highcharts.com/highstock/plotOptions.line.gapSize) **should not** affect line: 

> Defines when to display a gap in the graph. A gap size of 5 means that if the distance between two points is greater than five times that of the two closest points, the graph will be broken.

In case of two points, the above will not break the line because distance between two closest points (and only points in the graph) is the same as the furthest points.

I agree, it looks strange, but shouldn't `null` point be used in this case?

**Comment by mynameiswhat1** [comment]
Hello,
Wasn't this issue going to be solved in 5.0.12? Looking at the fixed bugs list for that version, I am not able to see this issue. Do you have an idea when it will get fixed? We were really counting on that realease for this bug fix.
Thank you.

**Comment by mynameiswhat1** [comment]
Hello,
Do you have an estimation for when this bug will be fixed? We have made commitments based on the announcement that it would be fixed in release 5.0.12 of Highcharts, however this was not the case. 
Thank you very much.

**Comment by pawelfus** [comment]
Hi @mynameiswhat1 

My apologies for the delay. I am not sure if this is a bug after all so it's not fixed. Workaround is to set `series.getExtremesFromAll` to true, demo: http://jsfiddle.net/w5cxn8jr/1/ Downside of this solution is yAxis scale, which will consider full dataset into extremes, not only the visible range.

**Comment by mynameiswhat1** [comment]
Hello @pawelfus,
Thank you for your reply, however your demo is not working due to the local reference to Highcharts. I've taken your suggestion into account in my demo and, as can be seen, the problem was not solved by setting the getExtremesFromAll property to to true: http://jsfiddle.net/gvj1d0mg/ 
Thank you very much.

**Comment by pawelfus** [comment]
It should be set as `series.getExtremesFromAll`, not `series.dataGrouping.getExtremesFromAll`, see updated demo: http://jsfiddle.net/gvj1d0mg/1/

**Comment by mynameiswhat1** [comment]
Hello @pawelfus,
Using your last demo, and following your suggestion, you can see, by using the navigator, that the chart is not correctly rendered and, also, for some time intervals where we expected to see chart lines, there are none.

I believe that this is a bug, that cannot be "worked around" with this property. It makes no sense that you are selecting an interval with no data, and the chart shows a line, keeping in mind that even the navigator shows the data gap.

When will a fix be available for this bug?
Thank you very much.

**Comment by mynameiswhat1** [comment]
Hello @pawelfus,
I believe that this cannot be solved with workarounds since, by setting the property as you previously suggested, it will break in other ways, as can be seen in the following demo and screen shots taken from it:

http://jsfiddle.net/gvj1d0mg/3/

![Image of Issue](http://preview.ibb.co/iqsyHa/noChart.jpg)

![Image of Issue](http://preview.ibb.co/kAO2Av/gaps.jpg)

I believe that this is a BUG and should be fixed as such since, in my opinion, it makes no sense that you select an interval, using the navigator, that has no data, and a line is shown in the chart, whereas  in the navigator the data gap is clearly visible.
When will there be a fix for this BUG?
Thank you very much.

**Comment by mynameiswhat1** [comment]
Hello,
Sorry for the spam, but this issue was initialy reported on HighCharts forum on the 21st of April 2017: https://forum.highcharts.com/highstock-usage/line-visible-for-line-chart-with-navigator-no-values-t38621/
After that, it was tagged as a bug here, on Github on the 27th of April 2017. It's fix was then added to the 5.0.12 milestone and, when that milestone came out, this bug was not fixed. Like I've said before, some commitments have been made on our part regarding this issue and we were not able to deliver due to the bug not being fixed in Highcharts. Can you please provide a date for the correction of this bug?
Thank you very much.

**Comment by pawelfus** [comment]
Hi @mynameiswhat1 

You are right, my workaround will give strange results. In that case, we are back to the point where using `null` points is the best solution. For example: http://jsfiddle.net/w5cxn8jr/3/ - the problem with this solution is where to put null points, those should be generated in advance, according to the granularity. For example:

```
...

        [1492535700000, 6755], // 17:30
        [1492536600000, null], // 17:45
        [1492540200000, 6667],  //18:30
...
```

**Comment by mynameiswhat1** [comment]
Hello @pawelfus,
So when will the **BUG** be corrected?
Thank you.

**Comment by pawelfus** [comment]
I am working on it. It's hard to say when this will be fixed. As I said, I am still not convinced if this is a bug in the first place.

Could you try this solution and let me know your results? Take a look: http://jsfiddle.net/j20pm8my/

```javascript
(function(H) {
  H.wrap(H.Series.prototype, 'processData', function(p) {
    var ret = p.apply(this, Array.prototype.slice.call(arguments, 1));

    if (this.navigatorSeries) {
      this.closestPointRange = Math.min(this.navigatorSeries.closestPointRange, this.closestPointRange);
    }

    return ret;
  });
})(Highcharts);
```

**Comment by mynameiswhat1** [comment]
Hello @pawelfus ,
Sorry, but that does not solve the issue. Please take a look at this fiddle: http://jsfiddle.net/uerc3oh7/1/
Data grouping is initially enabled. If you set the navigator to the gapped area in the chart you will see that this time there is no line. However, if you toggle data grouping, the line will appear and will only disappear when you move the navigator extremes again. So we end up with the same issue as in the begining.
I understand that this might be a difficult BUG to correct. however, as it was said before, it came to your knowledge on the 21st of April, and a commitment for it's fix was made to release 5.0.12 of Highcharts and, as you know, that commitment was not met. For this reason, we were not able to honor our own commitments. Please, give top priority to the correction of this BUG, since almost 2 months have passed since the problem was reported, and commitments were made that were not met.
Thank you very much.

**Comment by pawelfus** [comment]
Hi @mynameiswhat1 

Thank you for the demo, could you try this one: http://jsfiddle.net/pbxpmbm2/2/ ?  Note: your demo didn't update dataGrouping.

Issue was considered before 5.0.12 release. As you can see my comment, it works exactly as described in the docs. Actually, I should have change label from bug to undecided/enhancement and remove 5.0.12 milestone reference.

> gapSize:
> Defines when to display a gap in the graph. A gap size of 5 means that if the distance between two points is greater than five times that of the two closest points, the graph will be broken.

There are only two points in your case, so line **should** be connected and this is **not a bug**. I understand, this looks confusing and I am trying to find any solution or at least a workaround for you. I am giving this issue the highest priority and I apologise for this situation.

**Comment by TorsteinHonsi** [comment]
As Pawel says, `gapSize` is working correctly according to the docs, but obviously that doesn't help you @mynameiswhat1.

I can see two possible solutions:
1. We introduce a new option, `gapUnit`, that can be set to either `relative` (current behaviour), or  `value` which introduces gaps based on the axis interval rather than the relative gap from closest point range. I think in some cases this would resolve the wobbly nature of `gapSize`, so that for example if you know you have hourly data, you can force gaps for all intervals greater than an hour. On the flip side, the setting need to be adapted to different densities of data sets, but we'll leave the default setting to `relative` for this case. This is a really simple implementation that, in my opinion, adds value. See http://jsfiddle.net/highcharts/r5saqed0/4/ for demo.

2. We change the current behaviour of `gapSize` so that it inspects the full data set when determining closestPointRange. Similar to what Pawel suggests above, but obviously takes data grouping into account.

What do you think?

**Comment by mynameiswhat1** [comment]
Hello @TorsteinHonsi and @pawelfus ,
I believe that the second option will be more robust and also intuitive for the gapSize concept.
Thank you

**Comment by TorsteinHonsi** [comment]
From our point of view, the first option is definately the robust one, as it is very simple and doesn't depend on varying data interval. So that is something we can implement right away. Can you use it?

**Comment by sapan0511** [comment]
Hi TorsteinHonsi  , 

I have tested our application with the code provided by you in option 1 and the fix works fine for us. Can you please include the fix in the next highcharts release.

Thank you

**Comment by DamianoPantani** [comment]
```
series.isCartesian = false;
series.processData(true);
chart.redraw();
```

This hack worked for me. Not sure how it affects other features tho.
