### ISSUE TITLE
Chrome crash with 3D bubble charts

### ISSUE THREAD

**Issue by ErcNovelT** [highcharts/highcharts#7054]
Hi guys,

I found an issue (I guess) on the bubble chart in the **highcharts v4.2**. When I use a gradient marker on the series, if I click a multiple time on the legend to show/hide a serie, at some point (10 times for example), **Chrome crashes**. The problem is really Chrome specific (I use the latest chrome version 60).

You can have a look to this fiddle [here](http://jsfiddle.net/4jnr5uhk/10/) to reproduce the issue with Chrome.

If you remove the marker for each the serie, the bug goes away.

Thanks for your insight.

**Comment by KacperMadej** [comment]
Hi,

Thank you for reporting.

The problem is visible on Chrome version 60 and Highcharts version under 5.0.0.
The problem is fixed in 5.0.0, so there's not much that could be done here - maybe next Chrome version will provide a solution - before version 60 the problem was not visible.

**Comment by ErcNovelT** [comment]
Hi,

thanks for your reply. There is no way to get the fix to apply to the 4.2 version?

**Comment by pawelfus** [comment]
It is very hard to find exact change between 4.x.x and 5.0.0 which fixes that issue. Version 5.0.0 was a mayor release with a lot of changes. If only version change was like 4.2.1 <-> 4.2.2 we could find responsible commit and prepare a workaround at least. In your case, I strongly recommend upgrade to the latest version.

**Comment by ErcNovelT** [comment]
Hi again,

thanks for you explanations. By the way, the issue is still here with **highcharts version 5**. To reproduce it, you just need to disable one gradient marker from a serie (the other series keep their gradient marker), then you click on the legend a multiple time and Chrome crashes.

See the updated fiddle [here](http://jsfiddle.net/4jnr5uhk/13/).

Thanks.

**Comment by pawelfus** [comment]
Thank you! That means we need to reopen issue and flag it properly.

**Comment by Mrkhagol** [comment]
I am having this issue. What's surprising is that it only fails in chrome and in desktop/laptop browser version. Tried on my old nexus 5 phone chrome(latest version) and works perfectly..no crash errors.
Firefox and IE works fine too.

**Comment by TorsteinHonsi** [comment]
Normalized demo with a fixed width and removed irrelevant code: http://jsfiddle.net/highcharts/8ff102cu/

Click the "Run" button. This always counts to 5 in my instance of Chrome, then crashes.

**Comment by TorsteinHonsi** [comment]
#### Workaround
The issue seems to be connected to the alpha opacity of the bubbles. To avoid the crashes, use solid colors: http://jsfiddle.net/highcharts/8ff102cu/1/
