### ISSUE TITLE
Exporting chart into an image results in ‘error when performing chart generation: please check your input data’

### ISSUE THREAD

**Issue by PaulDalek** [highcharts/highcharts#7614]
#### Expected behaviour
Adding an image with renderer.image function on load event in exporting.chartOptions should not disrupt exporting chart into image.

#### Actual behaviour
Adding an image with renderer.image function on load event in exporting.chartOptions often results in ‘error when performing chart generation: please check your input data’

#### Live demo with steps to reproduce
http://jsfiddle.net/agwmtz8o/

1. Click ‘Download PNG image’

**Comment by pawelfus** [comment]
Our demos have the same issue, try to download image of this demo: https://www.highcharts.com/demo/combo-timeline

**Comment by gaffardremy** [comment]
I have the same problem, it works 1 time out of 5

DEMO : 
http://jsfiddle.net/agwmtz8o/1/

**Comment by TorsteinHonsi** [comment]
@cvasseng This one applies to https://github.com/highcharts/node-export-server

**Comment by cvasseng** [comment]
That's an interesting one. Looks like it's sometimes timing out waiting for the images to load, it may not be fixable without increasing the timeout on the server (set to 2.5 seconds currently IIRC).

**Comment by mousssaab** [comment]
with adding timeout on the function export that resolve the problem, That's a rotten thing to do.

**Comment by XWB** [comment]
Well, it worked for years. Does that mean the timeout on the server was decreased recently?

**Comment by cvasseng** [comment]
It should be resolved now. If any of you still experience the issue, please let us know.

**Comment by XWB** [comment]
Seems to be working again. Thank you!

**Comment by cvasseng** [comment]
That's good to hear!

Should the problem re-surface please feel free to reopen this issue.

**Comment by SaurabhKumarr** [comment]
exporter.export(chartArr.chartData, (err, res) => {
      chartArr.png = res.data;
      resolve();        
})
can any one tell me where to add timeout

**Comment by pawelfus** [comment]
Hi @SaurabhKumarr - could you contact our support:  https://www.highcharts.com/support ? Thanks!

**Comment by paulo-raca** [comment]
Looks like this problem is back. I noticed it for the first time today

**Comment by pawelfus** [comment]
Hi @paulo-raca - that a temporary problem with our exporting server, everything should be fine again. Could you confirm?

**Comment by paulo-raca** [comment]
Thank you!

**Comment by micronaut** [comment]
Hi.  We are getting the same error today for PNGs.  JPEGs seem to be OK.

**Comment by pawelfus** [comment]
Thanks for reporting! We are investigating this.

**Comment by cvasseng** [comment]
We deployed another fix a few hours ago, and things seem to be properly resolved now. We're keeping a close eye on it in case it starts acting up again.

**Comment by markathomas** [comment]
I only see a version in Git for 2.0.15 which I'm assuming doesn't have the latest fix?  How to apply without an upgrade available?

**Comment by cvasseng** [comment]
@markathomas: the express update is the fix. The issue came from one of the parser libraries express depends on (the `qs` library). The updated express version also updated this library to version 6.5.2 which had a fix for the issue. 

We'll publish the update on NPM and tag the release early next week, we wanted to be sure the issue was actually gone first. 

The easiest way of deploy it prior to the NPM publish and Git tag would be to clone master and run `npm install && npm link`, or point directly to Git in your package dependency if you're using it as a module. I'd recommend waiting though unless you're seeing the same issue on your own deployment.

**Comment by markathomas** [comment]
Thanks for the update.  I've already re-built using Git master but still experience the issue randomly.  About 1:8 is failing now.  We're implemented a retry mechanism for the time being.  If you want any help debugging just ask.

**Comment by cvasseng** [comment]
It's likely you're having a separate issue from the timeout problems we had on the official service.

Could you please open an issue on [the issue tracker](https://github.com/highcharts/node-export-server/issues) for the export server, and include the error output you're getting (if any)?

**Comment by sebastianbochan** [comment]
_Internal note_
New issue is created here: https://github.com/highcharts/node-export-server/issues/166

**Comment by zwmmm** [comment]
@cvasseng How to set the timeout period

**Comment by pawelfus** [comment]
Hi @zwmmm 

Did you setup your own exporting server? Or do you refer our exporting server (as the original question)? If you have your own exporting server, please contact our [support](https://www.highcharts.com/blog/support/). In case you refer our exporting server - you can not change timeout on our server.

**Comment by zwmmm** [comment]
@pawelfus Thank you, I have already located the problem, thank you for your reply

**Comment by maursam** [comment]
Hi, the error "0x04 error when performing chart generation: please check your input data" it's again today.

**Comment by sebastianbochan** [comment]
Hi @maursam,
Please share your live example of a chart and contact with us by one of our support channel (forum  / stackoverflow or email).

**Comment by maursam** [comment]
Thanks for your message, may be the error was due to exporting server, two hours ago after the error is showing this disappeared,

Thank you again,

Mauricio
.
